version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/20250730-flask
hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: root